version: '3'
services:
    backend:
        build: .
        image: gearsmotion789/canyoncreeklidar
        container_name: canyoncreeklidar_container
        ports:
            - 5000:5000
        volumes:
            - ~/.aws/credentials:/root/.aws/credentials
