version: '3'
services:
    backend:
        build: .
        image: tobyloki/canyoncreeklidar
        container_name: canyoncreeklidar
        ports:
            - 3000:80
        volumes:
            - ~/.aws/credentials:/root/.aws/credentials
